### ISSUE TITLE
app.use() requires middleware functions

### ISSUE THREAD

**Issue by kewisch** [tomdionysus/foaas#110]
Maybe you should consider fixating some of the dependency versions. It seems there are some API changes in express and related packages. Getting this:

```
TypeError: app.use() requires middleware functions
  at EventEmitter.use (/Users/kewisch/github/foaas/node_modules/express/lib/application.js:209:11)
  at EventEmitter.wrappedAppUse [as use] (/Users/kewisch/github/foaas/node_modules/newrelic/lib/instrumentation/express.js:348:11)
  at Object.module.exports.register (/Users/kewisch/github/foaas/lib/filters/i18n.coffee:17:9)
  at FOAAS.module.exports.FOAAS.loadFilters (/Users/kewisch/github/foaas/lib/foaas.coffee:90:14)
  at FOAAS.loadFilters (/Users/kewisch/github/foaas/lib/foaas.coffee:1:1)
  at new FOAAS (/Users/kewisch/github/foaas/lib/foaas.coffee:42:6)
  at Object.<anonymous> (/Users/kewisch/github/foaas/lib/server.coffee:6:13)
  at Object.<anonymous> (/Users/kewisch/github/foaas/lib/server.coffee:1:1)
  at Module._compile (module.js:456:26)
```

**Comment by morozgrafix** [comment]
ran into the same error :(

**Comment by DuncanRowland** [comment]
Have pushed a fix, but very simple edit to pin.
https://github.com/tomdionysus/foaas/pull/117/files

**Comment by tomdionysus** [comment]
All done.
